# Generated by Django 3.2.19 on 2024-05-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetailsDevis',
            fields=[
                ('id_details', models.AutoField(primary_key=True, serialize=False)),
                ('quantite', models.FloatField(blank=True, null=True)),
                ('prix_unitaire', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'details_devis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id_devis', models.AutoField(primary_key=True, serialize=False)),
                ('prix_total', models.FloatField()),
                ('date_debut_construction', models.DateField(blank=True, null=True)),
                ('date_fin_construction', models.DateField(blank=True, null=True)),
                ('date_devis', models.DateField(blank=True, null=True)),
                ('pourcentage', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'devis',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finition',
            fields=[
                ('id_finition', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('pourcentage', models.FloatField()),
            ],
            options={
                'db_table': 'finition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id_prestation', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle', models.CharField(max_length=100, unique=True)),
                ('prix_unitaire', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'prestation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Travaux',
            fields=[
                ('id_travaux', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'travaux',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TypeMaison',
            fields=[
                ('id_type', models.AutoField(primary_key=True, serialize=False)),
                ('duree', models.FloatField(blank=True, null=True)),
                ('libelle', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'type_maison',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id_unite', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'unite',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=100, null=True)),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'utilisateurs',
                'managed': False,
            },
        ),
    ]
