# Generated by Django 3.2.19 on 2024-05-13 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('btp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devis',
            options={'managed': True},
        ),
    ]
