TRUNCATE TABLE maison_temp RESTART IDENTITY CASCADE;
TRUNCATE TABLE devis_temp RESTART IDENTITY CASCADE;
TRUNCATE TABLE paiement_temp RESTART IDENTITY CASCADE;
TRUNCATE TABLE details_devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE details_construction RESTART IDENTITY CASCADE;
TRUNCATE TABLE paiement RESTART IDENTITY CASCADE;
TRUNCATE TABLE devis RESTART IDENTITY CASCADE;
TRUNCATE TABLE lieu RESTART IDENTITY CASCADE;
TRUNCATE TABLE type_maison RESTART IDENTITY CASCADE;
TRUNCATE TABLE finition RESTART IDENTITY CASCADE;
TRUNCATE TABLE travaux RESTART IDENTITY CASCADE;
TRUNCATE TABLE unite RESTART IDENTITY CASCADE;
TRUNCATE TABLE utilisateurs RESTART IDENTITY CASCADE;

INSERT INTO utilisateurs(numero, email, mot_de_passe, role) VALUES 
    ('0344881819', 'email@email.com', 'mdp', 0);
